### ISSUE TITLE
hub-spoke Sample Deployment Fails

### ISSUE THREAD

**Issue by gottagetgit** [mspnp/samples#108]
Relating to this sample:
https://github.com/mspnp/samples/blob/master/solutions/azure-hub-spoke/azuredeploy.json

I've attempted to deploy it a few times, and it fails. 

The error message is odd. It fails to deploy the bastion service on the error "another operation is in progress" on a dependent resource.

Redeploying it fails too because it uses a GUID() as a resource name, and attempts to create the Azure Firewall Workbook again when one already exists. Another error. Deleting the workbook and redeploying again causes another error on attempting to delete the AzureFirewallSubnet while the firewall on it already exists.

Deleting everything and deploying the whole thing again causes another Bastion service error. Same as the last time.

Perhaps someone else can try deploying this and see if it's just me.

**Comment by neilpeterson** [comment]
@gottagetgit thanks for opening the issue, looking into it now.

**Comment by gottagetgit** [comment]
@neilpeterson  thanks for checking

Here is the error that I am receiving along with the code I used to deploy:
[Error screenshot](https://imgur.com/a/smDj7PA)

I deployed to eastus region. Passed no parameters. As per the instructions here:
[Instructions](https://docs.microsoft.com/en-us/samples/mspnp/samples/hub-and-spoke-deployment/)

I will try another region. Perhaps eastus is too slow.

**Comment by neilpeterson** [comment]
Thanks @gottagetgit, I was able to deploy into eastus with no issue. Let me know how it works out in a second region. Perhaps we can troubleshoot together if the issue persists.

**Comment by gottagetgit** [comment]
I will keep trying and let you know. A new challenge for the second region...
[New error](https://imgur.com/a/4W3zBga)

I'll see what's up.

**Comment by neilpeterson** [comment]
Thanks @gottagetgit I believe that I have been able to reproduce the initial issue and am looking into it now.

**Comment by gottagetgit** [comment]
The deployment succeeded in "centralus" once I used a different name for the resource group.

So it seems unreliable, but persistence can get it to work.

**Comment by neilpeterson** [comment]
@gottagetgit I was able to reproduce the initial error once, the issue seems transient / no longer present to me. I have fixed a few things that were causing issue on re-deployment:

https://github.com/mspnp/samples/pull/109

Thanks again. I'm going to close this but will keep my eye in it.
