### ISSUE TITLE
SLAEstimator

### ISSUE THREAD

**Issue by dtometzki** [mspnp/samples#112]
Hello,

i use npm 7.6.0 and i try to buld SLAEstimator but it fails 
I go to
/samples/Reliability/SLAEstimator/SLAEstimator/SLAEstimator/ClientApp
run npm install
npm start
then i got: 
Failed to compile.

./src/components/Styles.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/components/Styles.css)
Error: Can't resolve '/images/downarrow.png' in '/home/damian/samples/Reliability/SLAEstimator/SLAEstimator/SLAEstimator/ClientApp/src/components'

What can i do ?

Best regards
Damian

**Comment by hallihan** [comment]
Did you try building and running the solution at: /Reliability/SLAEstimator/SLAEstimator/SLAEstimator.sln ?

**Comment by edm-ms** [comment]
It would be helpful if there were instructions for how to build and run the solution. Not everyone is a developer, and although these tasks may seem intuitive and simple, a non-dev would never be able to figure out how to get this running locally on their machine.

**Comment by KevSmiff** [comment]
> It would be helpful if there were instructions for how to build and run the solution. Not everyone is a developer, and although these tasks may seem intuitive and simple, a non-dev would never be able to figure out how to get this running locally on their machine.

Absolutely I'm an infra architect with little coding knowledge. Please can someone help me with this! I think I need VS Code which I've installed, now what? 🆘

**Comment by turb0chrg** [comment]
I am also struggling with this solution. I believe you need Visual Studio 2019 as there is a soln file in there. I built the C# solution and then ran the react app from ClientApp but get errors right away.

I'm glad I'm not the only one that finds making this work difficult!

**Comment by ckittel** [comment]
@david-stanford -- do you have someone you'd like to assign to getting this functioning?

**Comment by ckittel** [comment]
@david-stanford / @robbyatmicrosoft -- Is there someone that should be assigned to this question/work from WAF?  If this is something that Content Engineering should address, can we get it allocated for an upcoming sprint?

**Comment by ckittel** [comment]
Bumping again for @david-stanford / @robbyatmicrosoft.
