### ISSUE TITLE
Incorrect SLA value for Azure Active Directory

### ISSUE THREAD

**Issue by gsriramit** [mspnp/samples#156]
Hi,

The SLA Data JSON file carries an old value (may be), for the AAD service
Reference:

"CategoryName": "Identity AD", 
   "Services": [      {  
      "CategoryName": "Identity AD",   
     "Name": "Active Directory",   
     "Notes": "Azure AD Basic or Premium required for SLA",  
      "ImageFile": "activedirectory.png",  
      **"SLA": 99.900,**
        "SlaAgreementUrl": "https://azure.microsoft.com/support/legal/sla/active-directory"      }

The value should be 99.99%. The provided SlaAgreementUrl has the updated value.

**Comment by adamyager** [comment]
Edit the JSON at Data -> 2FSLA_data.json to the new value. Build and deploy and you now have the values that can change.
You can also add new services in the same way

**Comment by ckittel** [comment]
@adamyager is correct.  The SLA values are just samples, and not designed to reflect our actual SLAs.

**Comment by gsriramit** [comment]
@adamyager & @ckittel, Thanks for the information
