### ISSUE TITLE
DeployVPNGateway misssing in bicep sample

### ISSUE THREAD

**Issue by DominicBoettger** [mspnp/samples#169]
The bicep sample does not contain the provisioning of the VPNGateway.

**Comment by ckittel** [comment]
Indeed, the instructions imply that they do (optionally), but doesn't look like the bicep templates actually do.  @neilpeterson can you have someone take a look at this?

**Comment by neilpeterson** [comment]
@ckittel apologies, I cannot prioritize at this time and not sure whom I could route too. Some thoughts:

- Decompile the ARM template and suck out the gateway pieces. Would still take some time but may help.
- Update the surrounding guidance to indicate that the gateway is not included in the Bicep version (I should have done this, apologies).
- Remove the Bicep version.

**Comment by ckittel** [comment]
@hallihan I propose we go with the second bullet point option for this.  Just be clear about what it does and doesn't include in the bicep version for now.

**Comment by svaenn** [comment]
I was trying out the bicep and created a pull request with the first bullet point option.

**Comment by magrande** [comment]
@DominicBoettger  Thanks for raising this issue. First bullet point option was applied. Thanks @svaenn for your PR
