### ISSUE TITLE
Log Analytics No Longer Has a Free SKU

### ISSUE THREAD

**Issue by gottagetgit** [mspnp/samples#171]
https://github.com/mspnp/samples/blob/01500c8e42cdf7aa19846d46001be9cba1ca4877/solutions/secure-hybrid-network/nestedtemplates/azure-network-azuredeploy.json#L116

The deployment of this sample fails because the Free SKU for Log Analytics Workspace no longer exists.

**Comment by gottagetgit** [comment]
Apparently, only some customers have access to a legacy SKU like this. 

https://docs.microsoft.com/en-us/azure/azure-monitor//usage-estimated-costs#moving-to-the-new-pricing-model

**Comment by tutul2010** [comment]
HI ,
I am facing same issue and How to update logAnalytics part at below 
https://github.com/mspnp/samples/blob/master/solutions/basic-web-app/azuredeploy.json

Thanks,

**Comment by gottagetgit** [comment]
cc @neilpeterson

**Comment by PramodValavala-MSFT** [comment]
Looks like the newer tier that should work is `PerGB2018` instead. I tried changing the tier and can confirm deployment works. Here is the PR for the same - mspnp/samples#172

**Comment by hallihan** [comment]
Fixed in #172
