### ISSUE TITLE
displayname should not be included

### ISSUE THREAD

**Issue by lunar87** [mspnp/samples#226]
In https://github.com/mspnp/samples/blob/main/solutions/azure-hub-spoke-connected-group/bicep/modules/avnm.bicep, line 118 and 149 with displayname should not be included. Per https://learn.microsoft.com/en-us/azure/templates/microsoft.network/2022-05-01/networkmanagers/connectivityconfigurations?pivots=deployment-language-bicep not part of schema.

**Comment by ckittel** [comment]
@mbrat2005 - on your next freshness review, can you please take care of this linter warning?

**Comment by mbrat2005** [comment]
Sure Chad, sorry I missed this one. I'll make that update

**Comment by ckittel** [comment]
No rush of course, and thanks!

**Comment by mbrat2005** [comment]
Fixed in PR #236
