### ISSUE TITLE
Missing index.html after build

### ISSUE THREAD

**Issue by Aurel-Bruno** [mspnp/samples#53]
Hello,

I build successfully but when I try to run the application I have a message indicating that I miss the file index.html. You will find the details (screenshots) in attachment.
[sla_estimator_issue.docx](https://github.com/mspnp/samples/files/5378308/sla_estimator_issue.docx)

**Comment by magrande** [comment]
@Aurel-Bruno  Thank you for raising this issue. I will look into it.

**Comment by magrande** [comment]
@Aurel-Bruno  I wasn't able to repro the issue, I tried using IISExpress in production mode.

  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      }
    }
  }

How are you trying to run the application ?   Can you try publishing it to local IIS ?

Take a look at this:

https://stackoverflow.com/questions/51989817/dotnet-build-get-error-could-not-return-the-default-page-index-html

**Comment by magrande** [comment]
I'm going to proceed and close the issue, since there is no action needed on our end. If this is still happening, feel free to re open it, or create a new one.
